import type { BasePhoto, GalleryFilter } from "@/types/photo";

export const categories = [
  "Todo",
  "Fauna",
  "Arquitectura",
  "Paisaje",
  "Personas",
  "Meteorología",
] as const satisfies readonly GalleryFilter[];

export const photos = [
  {
    id: 1,
    title: "Trío en la niebla",
    category: "Fauna",
    year: "2023",
    image: "/1.webp",
    color: "secondary",
    description: "Tres caballos, un instante de ternura en la bruma.",
  },
  {
    id: 3,
    title: "El ruido del cielo",
    category: "Meteorología",
    featured: true,
    year: "2024",
    image: "/3.webp",
    color: "chart-3",
    description:
      "Un relámpago atraviesa las nubes encendidas, como un grito eléctrico en medio del crepúsculo.",
  },
  {
    id: 4,
    title: "Silencio sobre la roca",
    category: "Fauna",
    year: "2025",
    image: "/4.webp",
    color: "accent",
    description: "Una gaviota contempla el abismo en calma absoluta.",
  },
  {
    id: 5,
    title: "Banquete en el bosque",
    category: "Fauna",
    year: "2025",
    image: "/5.webp",
    color: "secondary",
    description: "Una ardilla saborea su tesoro en la alfombra del bosque.",
  },
  {
    id: 6,
    title: "Sevilla entre reflejos y alturas",
    category: "Arquitectura",
    featured: true,
    year: "2025",
    image: "/6.webp",
    color: "chart-3",
    description:
      "La ciudad respira entre ríos, puentes y torres, donde lo moderno y lo histórico se dan la mano.",
  },
  {
    id: 7,
    title: "Reflejo sereno",
    category: "Fauna",
    year: "2025",
    image: "/7.webp",
    color: "accent",
    description: "Un cisne reposa con la calma de un poema.",
  },
  {
    id: 11,
    title: "Alas sobre púrpura",
    category: "Fauna",
    year: "2025",
    image: "/11.webp",
    color: "accent",
    description: "Dos mariposas visitan los cardos en plena floración.",
  },
  {
    id: 12,
    title: "Alas de otoño",
    category: "Fauna",
    year: "2025",
    image: "/12.webp",
    color: "chart-3",
    description: "Una mariposa descansa sobre hojas teñidas de estación.",
  },
  {
    id: 13,
    title: "Donde el lago abraza la tierra",
    category: "Paisaje",
    featured: true,
    year: "2025",
    image: "/13.webp",
    color: "accent",
    description:
      "Un lago tranquilo se extiende entre colinas cubiertas de brezo.",
  },
  {
    id: 16,
    title: "El centinela del océano",
    category: "Paisaje",
    year: "2025",
    image: "/16.webp",
    color: "chart-3",
    description:
      "Una formación rocosa solitaria se alza entre las aguas, como un guardián ancestral frente al paso del tiempo.",
  },
  {
    id: 17,
    title: "Guardianes del acantilado",
    category: "Paisaje",
    featured: true,
    year: "2025",
    image: "/17.webp",
    color: "accent",
    description:
      "Una torre solitaria se asoma al vacío, mientras los acantilados se desvanecen en la bruma del Atlántico.",
  },
  {
    id: 19,
    title: "Puente hacia el alma de Oporto",
    category: "Arquitectura",
    featured: true,
    year: "2024",
    image: "/19.webp",
    color: "chart-3",
    description:
      "El puente de Oporto une historia y modernidad sobre las aguas del Duero.",
  },
  {
    id: 21,
    title: "Última parada: la noche",
    category: "Arquitectura",
    featured: true,
    year: "2024",
    image: "/21.webp",
    color: "secondary",
    description:
      "Un tranvía atraviesa la noche de Oporto, mientras la ciudad respira entre sombras y encuentros.",
  },
  {
    id: 23,
    title: "Luz, historia y espíritu navideño",
    category: "Arquitectura",
    year: "2024",
    image: "/23.webp",
    color: "chart-3",
    description: "La Navidad transforma Braga en un túnel de luz y tradición.",
  },
  {
    id: 24,
    title: "Entre espirales y campanadas",
    category: "Arquitectura",
    year: "2024",
    image: "/24.webp",
    color: "accent",
    description:
      "La Navidad une pasado y futuro frente al ayuntamiento de Oporto.",
  },
  {
    id: 26,
    title: "La torre que vigila los sueños",
    category: "Arquitectura",
    year: "2024",
    image: "/26.webp",
    color: "chart-3",
    description:
      "La Torre de los Clérigos se alza sobre Oporto mientras el día se despide con luz tenue.",
  },
  {
    id: 27,
    title: "Donde el cielo se encuentra con la ciudad",
    category: "Arquitectura",
    year: "2024",
    image: "/27.webp",
    color: "accent",
    description:
      "Un músico acompaña el atardecer en Oporto mientras la ciudad se despide del día.",
  },
  {
    id: 29,
    title: "La flecha dorada entre pasos urbanos",
    category: "Arquitectura",
    year: "2024",
    image: "/29.webp",
    color: "chart-3",
    description:
      "Un mojón del Camino de Santiago marca el rumbo entre adoquines y miradas al horizonte.",
  },
  {
    id: 30,
    title: "Refugio entre montañas",
    category: "Paisaje",
    featured: true,
    year: "2024",
    image: "/30.webp",
    color: "secondary",
    description:
      "Un valle escondido respira entre bosques y tejados rojos, bajo la luz suave de la montaña.",
  },
  {
    id: 31,
    title: "Aveiro, la Venecia portuguesa",
    category: "Arquitectura",
    year: "2024",
    image: "/31.webp",
    color: "secondary",
    description:
      "Las góndolas navegan por Aveiro entre puentes, fachadas y luz de invierno.",
  },
  {
    id: 35,
    title: "El murmullo de Ordesa",
    category: "Paisaje",
    featured: true,
    year: "2022",
    image: "/35.webp",
    color: "secondary",
    description:
      "La cascada de la Cola de Caballo en Ordesa invita al silencio y la contemplación entre rocas y espuma.",
  },
  {
    id: 37,
    title: "Donde termina el paso",
    category: "Paisaje",
    year: "2025",
    image: "/37.webp",
    color: "accent",
    description:
      "Dos pies descalzos se funden con la arena mojada, en un instante sereno entre tierra y mar.",
  },
  {
    id: 41,
    title: "Corte eléctrico sobre la ciudad",
    category: "Meteorología",
    featured: true,
    year: "2024",
    image: "/41.webp",
    color: "secondary",
    description:
      "Un relámpago rasga el cielo nocturno, iluminando fugazmente las siluetas urbanas bajo su trazo eléctrico.",
  },
  {
    id: 43,
    title: "La estación del silencio",
    category: "Arquitectura",
    year: "2025",
    image: "/43.webp",
    color: "chart-3",
    description:
      "Las vías se extienden hacia las montañas desde una estación tranquila, invitando al viaje interior y exterior.",
  },
  {
    id: 44,
    title: "Rojo sobre asfalto",
    category: "Personas",
    year: "2025",
    image: "/44.webp",
    color: "accent",
    description:
      "Un piloto retro irrumpe en la ciudad con estilo y actitud, como salido de una escena de acción.",
  },
  {
    id: 46,
    title: "El acordeón y el abismo",
    category: "Personas",
    year: "2025",
    image: "/46.webp",
    color: "chart-3",
    description:
      "Un músico solitario llena de música los acantilados de Moher, donde la tierra se encuentra con el cielo.",
  },
  {
    id: 48,
    title: "Entrada imaginaria",
    category: "Arquitectura",
    year: "2025",
    image: "/48.webp",
    color: "secondary",
    description:
      "Una puerta dibujada en tiza transforma un muro común en un umbral hacia lo posible.",
  },
  {
    id: 49,
    title: "Flores, sol y motor clásico",
    category: "Arquitectura",
    year: "2025",
    image: "/49.webp",
    color: "chart-3",
    description:
      "Un Mini clásico se detiene entre flores y luz, evocando tardes de verano y elegancia retro.",
  },
  {
    id: 50,
    title: "Entre ladrillos y cambio",
    category: "Arquitectura",
    year: "2025",
    image: "/50.webp",
    color: "secondary",
    description:
      "Una calle de Dublín vibra entre historia, obras y movimiento cotidiano.",
  },
  {
    id: 51,
    title: "Susurros del monasterio",
    category: "Arquitectura",
    year: "2025",
    image: "/51.webp",
    color: "secondary",
    description:
      "Una antigua iglesia irlandesa se alza bajo cielos densos, guardando siglos de silencio.",
  },
] satisfies BasePhoto[];
